const isDev = process.env.REACT_APP_NODE_ENV === "development";
const baseUrl = isDev ? "http://localhost:5000/" : "https://server-thrumming-waterfall-7530.fly.dev/";

export const urlConstants = {
  getProblem: baseUrl + "api/problems/id",
  getProblems: baseUrl + "api/problems",
  getCompetition: baseUrl + "api/competitions/id",
  getCompetitions: baseUrl + "api/competitions",
  createCompetition: baseUrl + "api/competitions/create",
  updateCompetition: baseUrl + "api/competitions/update",
  registerUserForCompetiton: baseUrl + "api/competitions/registeruser",
  addUserForCompetiton: baseUrl + "api/competitions/adduser",
  getCompetitionOverview: baseUrl + "api/competitions/overview",
  runCode: baseUrl + "api/code/run",
  submitCode: baseUrl + "api/code/submit",
  loginUser: baseUrl + "api/auth/login",
  loginMicrosoft: baseUrl + "api/auth/microsoft",
  registerUser: baseUrl + "api/auth/register",
  getSocialProfile: baseUrl + "api/social-profile/id",
  updateSocialProfile: baseUrl + "api/social-profile/update",
  updateAvatarUrl: baseUrl + "api/images/update",
  uploadAvatarUrl: baseUrl + "api/images/upload",
  updateUserProfile: baseUrl + "api/users/update",
  getUsers: baseUrl + "api/users",
  singleUser: baseUrl + "api/users",
  createUser: baseUrl + "api/users/create",
  problem: baseUrl + "api/problems",
  user: baseUrl + "api/users",
  createProblem: baseUrl + "api/problems/create",
  updateProblem: baseUrl + "api/problems/update",
  getCompetitionProblem: baseUrl + "api/competitions/problem/id",
  getTimestamp: baseUrl + "api/competitions/timestamp",
  getUserSubmissions: baseUrl + "api/competitions/getusersubmisions",
  getAllSubmissions: baseUrl + "api/competitions/getallsubmisions",
  getLeaderboard: baseUrl + "api/competitions/getleaderboard",
  getTopicCounts: baseUrl + "api/problems/topic-counts",
  getUsers: baseUrl + "api/users",
  getSearchedProblems: baseUrl + "api/problems/search",
  getAllNotifications: baseUrl + "api/notifications",
  createNotification: baseUrl + "api/notifications/create",
  markNotificationAsRead: baseUrl + "api/notifications/mark-as-read",
  googleLogin: baseUrl + "api/auth/google-login",
  verifyOtp: baseUrl + "api/auth/verify-otp",
  getDailyProblem: baseUrl + "api/problems/daily-problem",
  getLists: baseUrl + "api/lists",
  updateList: baseUrl + "api/lists/update",
  createList: baseUrl + "api/lists/create",
  deleteList: baseUrl + "api/lists/delete",
  resendOTP: baseUrl + "api/auth/resend-otp",
  resetPassword: baseUrl + "api/auth/reset-password",
  updateSocialImage: baseUrl + "api/social-profile/upload-profile-image",
  getSocialImage: baseUrl + "api/social-profile/download-profile-image",
  deleteSocialImage: baseUrl + "api/social-profile/delete-profile-image",
  getSignedUrl: baseUrl + "api/images/signed-url",
};

export const adminRoutes = {
  getProblems: baseUrl + "api/problems/admin",
  getProblemIds: baseUrl + "api/problems/admin/ids",
  adminUserId: baseUrl + "api/users/admin",
};
